// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQTqa-JLa66c9iBRfNgXAL72N4oc3a8H8',
    appId: '1:47409456590:web:4bcf5e32d284c22652f79f',
    messagingSenderId: '47409456590',
    projectId: 'crud-158f9',
    authDomain: 'crud-158f9.firebaseapp.com',
    storageBucket: 'crud-158f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjxT-TOqT-6B4QwSVGkVA_FlauT9VdV_s',
    appId: '1:47409456590:ios:88be6216354ab0b152f79f',
    messagingSenderId: '47409456590',
    projectId: 'crud-158f9',
    storageBucket: 'crud-158f9.firebasestorage.app',
    iosBundleId: 'com.example.fireCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjxT-TOqT-6B4QwSVGkVA_FlauT9VdV_s',
    appId: '1:47409456590:ios:88be6216354ab0b152f79f',
    messagingSenderId: '47409456590',
    projectId: 'crud-158f9',
    storageBucket: 'crud-158f9.firebasestorage.app',
    iosBundleId: 'com.example.fireCrud',
  );
}
